"""initial_schema

Revision ID: 12ab7a49a243
Revises: 
Create Date: 2025-12-09 07:32:24.409911

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '12ab7a49a243'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create pgvector extension
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(length=10000), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('memory_type', sa.Enum('EPISODIC', 'SEMANTIC', 'PROCEDURAL', name='memorytype'), nullable=False),
    sa.Column('observation_type', sa.Enum('ERROR', 'INSTRUCTION', 'DECISION', 'CODE_CHANGE', 'INSIGHT', 'TEST_RESULT', 'GENERAL', 'TOOL_OUTPUT', name='observationtype'), nullable=True),
    sa.Column('section', sa.Enum('STRATEGIES', 'SNIPPETS', 'PITFALLS', 'CONTEXT', 'PREFERENCES', name='sectiontype'), nullable=True),
    sa.Column('importance_score', sa.Float(), nullable=False),
    sa.Column('helpful_count', sa.Integer(), nullable=False),
    sa.Column('harmful_count', sa.Integer(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('citations', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=False),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memories_user_id'), 'memories', ['user_id'], unique=False)
    op.create_index('ix_memories_created_at', 'memories', ['user_id', sa.text('created_at DESC')], unique=False)
    op.create_index('ix_memories_last_accessed_at', 'memories', ['last_accessed_at'], unique=False)
    op.create_index('ix_memories_memory_type', 'memories', ['memory_type'], unique=False)
    # IVFFlat index for vector similarity search (requires populated table for optimal list count)
    op.execute("""
        CREATE INDEX ix_memories_embedding ON memories
        USING ivfflat (embedding vector_cosine_ops)
        WITH (lists = 100)
    """)
    op.create_table('reflection_state',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('accumulated_importance', sa.Float(), nullable=False),
    sa.Column('observations_since', sa.Integer(), nullable=False),
    sa.Column('last_reflection_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reflection_state')
    op.drop_index('ix_memories_embedding', table_name='memories')
    op.drop_index('ix_memories_memory_type', table_name='memories')
    op.drop_index('ix_memories_last_accessed_at', table_name='memories')
    op.drop_index('ix_memories_created_at', table_name='memories')
    op.drop_index(op.f('ix_memories_user_id'), table_name='memories')
    op.drop_table('memories')
    # Drop enums
    op.execute("DROP TYPE IF EXISTS memorytype")
    op.execute("DROP TYPE IF EXISTS observationtype")
    op.execute("DROP TYPE IF EXISTS sectiontype")
    # ### end Alembic commands ###
