"""add reflection_jobs table

Revision ID: 768c8f182893
Revises: 12ab7a49a243
Create Date: 2025-12-14 18:09:57.599689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '768c8f182893'
down_revision: Union[str, Sequence[str], None] = '12ab7a49a243'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reflection_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', name='reflectionjobstatus'), nullable=False),
    sa.Column('focus', sa.String(), nullable=True),
    sa.Column('max_insights', sa.Integer(), nullable=False),
    sa.Column('force', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('insights_created', sa.Integer(), nullable=True),
    sa.Column('procedures_created', sa.Integer(), nullable=True),
    sa.Column('memories_analyzed', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('result_payload', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reflection_jobs_status'), 'reflection_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_reflection_jobs_user_id'), 'reflection_jobs', ['user_id'], unique=False)
    op.drop_index(op.f('ix_memories_created_at'), table_name='memories')
    op.drop_index(op.f('ix_memories_embedding'), table_name='memories', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index(op.f('ix_memories_last_accessed_at'), table_name='memories')
    op.drop_index(op.f('ix_memories_memory_type'), table_name='memories')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_memories_memory_type'), 'memories', ['memory_type'], unique=False)
    op.create_index(op.f('ix_memories_last_accessed_at'), 'memories', ['last_accessed_at'], unique=False)
    op.create_index(op.f('ix_memories_embedding'), 'memories', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index(op.f('ix_memories_created_at'), 'memories', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.drop_index(op.f('ix_reflection_jobs_user_id'), table_name='reflection_jobs')
    op.drop_index(op.f('ix_reflection_jobs_status'), table_name='reflection_jobs')
    op.drop_table('reflection_jobs')
    # ### end Alembic commands ###
